version: '3'
services:
  mysql:
    image: mysql:8.0.36
    env_file: ./env/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql   # aqui troca ./mysql-data pelo volume nomeado
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:7.2.4
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped
    depends_on:
      - app-1
      - app-2

  app-1: &app
    build:
      context: .   # aqui pode continuar sendo .
    volumes:
      - ~/.m2:/root/.m2
    image: arturoburigo/codechella:latestx
    env_file: ./env/app.env
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
  app-2:
    <<: *app

volumes:
  mysql-data:     # volume nomeado, gerenciado pelo Docker
